### ISSUE TITLE
[BUG/Help] 传输文本较长时，会返回一个event: ping

### ISSUE THREAD

**Issue by littlestone0806** [uni-openai/GLM-API#1]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

我是基于C#写的客户端，用http给后端请求chatstream时，比较短的对话都正常，但是长对话时，会返回一个event: ping，请问这个和后台的哪个位置有关系？目前我只能在前端用try catch处理一下，要不会出现json解析错误的问题

### Steps To Reproduce

private async Task GLMSendStream(string str)
        {
            string postdata =
                "{\"prompt\": \"" + str +
                "\", \"history\":" + history +
                ", \"top_p\":" + ucTrackBarTopp.Value +
                ", \"temperature\":" + ucTrackBarTemp.Value +
                ", \"max_length\":" + ucTrackBarMaxTokens.Value + "}";
            // 创建一个 HttpClient 实例
            var httpClient = new HttpClient();

            var postData = new StringContent(postdata, Encoding.UTF8, "application/json");
            var request = new HttpRequestMessage(HttpMethod.Post, ucTextBoxExAPI.InputText) { Content = postData };

            // 发送 POST 请求
            var response = await httpClient.SendAsync(request, HttpCompletionOption.ResponseHeadersRead);

            Stream stream = await response.Content.ReadAsStreamAsync();
            var streamReader = new StreamReader(stream, Encoding.UTF8);

            // 读取数据流
            while (!streamReader.EndOfStream)
            {
                try
                {
                    result = streamReader.ReadLine();
                    if (result != "")
                    {
                        result = result.Replace("data:", "");
                        JObject jo = JsonConvert.DeserializeObject<JObject>(result); ;
                        result = jo["message"].ToString();
                        if (result != result_old)
                        {
                            if (result.Length < result_old.Length)
                            {
                                data = result;
                                data = data.Substring(result_old.Length - 3);
                                this.Invoke((EventHandler)(delegate
                                {
                                    richTextBoxAnswer.Text = richTextBoxAnswer.Text.Remove(richTextBoxAnswer.Text.Length - 3);
                                    richTextBoxAnswer.AppendText(data);
                                }));
                                await Task.Delay(10);
                            }
                            else
                            {
                                data = result;
                                data = data.Substring(result_old.Length);
                                this.Invoke((EventHandler)(delegate
                                {
                                    richTextBoxAnswer.AppendText(data);
                                }));
                                await Task.Delay(10);
                            }
                            result_old = result;
                        }
                    }
                }
                catch (Exception ex)
                {

                }
                
            }
            result = result_old = data = "";
        }

### Environment

```markdown
- OS:windows
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by devilyouwei** [comment]
您好，这个问题我在js上并没有遇到，你可以使用类似is_json方法现判断下收到的字符串是否是json，只有是的情况下再做处理。我在GPT的接口上遇到过返回数据不是json无法格式化问题

**Comment by littlestone0806** [comment]
> 

好的，感谢
